# Generated by Django 4.0.3 on 2022-03-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_kitnet_t_inadimplente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitnet',
            name='cpf',
            field=models.CharField(max_length=14, unique=b'I01\n'),
        ),
    ]
