# Generated by Django 4.0.3 on 2022-03-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_kitnet_numkitnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitnet',
            name='Tam_Kitnet',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Medio', 'Medio'), ('Grande', 'Grande')], max_length=7),
        ),
    ]
