# Generated by Django 4.0.3 on 2022-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_kitnet_tam_kitnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitnet',
            name='NumKitnet',
            field=models.CharField(max_length=50, unique=b'I01\n', verbose_name='Numero do Kitnet'),
        ),
        migrations.AlterField(
            model_name='kitnet',
            name='Tam_Kitnet',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Medio', 'Medio'), ('Grande', 'Grande')], max_length=7, verbose_name='Tamanho do Kitnet'),
        ),
        migrations.AlterField(
            model_name='kitnet',
            name='Valor_Imovel',
            field=models.CharField(max_length=50, verbose_name='Valor Mensal do Imovel'),
        ),
        migrations.AlterField(
            model_name='kitnet',
            name='cpf',
            field=models.CharField(max_length=14, unique=b'I01\n', verbose_name='CPF do Titular'),
        ),
        migrations.AlterField(
            model_name='kitnet',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Titular'),
        ),
    ]
