# Generated by Django 4.0.3 on 2022-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_alter_kitnet_numkitnet_alter_kitnet_tam_kitnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitnet',
            name='Inadimplente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kitnet',
            name='T_Inadimplente',
            field=models.CharField(max_length=50),
        ),
    ]
