# Generated by Django 4.0.3 on 2022-03-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_alter_kitnet_inadimplente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitnet',
            name='Inadimplente',
            field=models.IntegerField(),
        ),
    ]
