# Generated by Django 4.0.3 on 2022-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_alter_kitnet_inadimplente_alter_kitnet_numkitnet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitnet',
            options={'ordering': ('NumKitnet', 'nome', 'cpf')},
        ),
        migrations.AlterField(
            model_name='kitnet',
            name='Inadimplente',
            field=models.PositiveIntegerField(),
        ),
    ]
