# Generated by Django 4.0.3 on 2022-03-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_alter_kitnet_options_alter_kitnet_inadimplente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitnet',
            name='Inadimplente',
            field=models.BooleanField(default=True),
        ),
    ]
