# Generated by Django 4.0.3 on 2022-03-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_alter_kitnet_inadimplente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitnet',
            name='Inadimplente',
        ),
        migrations.RemoveField(
            model_name='kitnet',
            name='T_Inadimplente',
        ),
    ]
